name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  broadcastCI:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CI }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }}
          
          Commit: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}

          Changes 👇👇👇
          https://github.com/${{ github.repository }}/commit/${{github.sha}}
  notifyTeam:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TEAM }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }} by ${{ github.actor }}
          Repository: ${{ github.repository }}
  notifyOwner:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'xpert0' }}
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.OWNER }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }}
          
          username: ${{ github.actor }}
          https://github.com/${{ github.actor }}
          
          repo: ${{ github.repository }}
          
          Changes 👇👇👇
          https://github.com/${{ github.repository }}/commit/${{github.sha}}
