name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  broadcastCI:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value
      id: value
      run: |
        echo "TEST=$(ls)" >> "$GITHUB_ENV"
        echo "TEST1=g" >> "$GITHUB_OUTPUT"
        cat $GITHUB_ENV
     
    - uses: appleboy/telegram-action@master
      env:
          TEST1: ${{ steps.value.outputs.TEST1 }}
      with:
        to: ${{ secrets.CI }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }}
          
          Commit: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}

          Changes 👇👇👇
          https://github.com/${{ github.repository }}/commit/${{github.sha}}

          "$TEST1"
          "${{ env.TEST1 }}"
          "${{ env.TEST }}"
  notifyTeam:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TEAM }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }} by ${{ github.actor }}
          Repository: ${{ github.repository }}
  notifyOwner:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'xpert0' }}
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.OWNER }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }}
          
          username: ${{ github.actor }}
          https://github.com/${{ github.actor }}
          
          repo: ${{ github.repository }}
          
          Changes 👇👇👇
          https://github.com/${{ github.repository }}/commit/${{github.sha}}

