name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  broadcastCI:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CI }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }}
          
          Commit: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}

          Changes 👇👇👇
          https://github.com/${{ github.repository }}/commit/${{github.sha}}
  notifyTeam:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TEAM }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }} by ${{ github.actor }}
          Repository: ${{ github.repository }}
  notifyOwner:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'xpert0' }}
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.OWNER }}
        token: ${{ secrets.TOKEN }}
        message: |
          ${{ github.event_name }}
          
          username: ${{ github.actor }}
          https://github.com/${{ github.actor }}
          
          repo: ${{ github.repository }}
          
          Changes 👇👇👇
          https://github.com/${{ github.repository }}/commit/${{github.sha}}
  bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Nix Shell
  # You may pin to the exact commit or the version.
  # uses: workflow/nix-shell-action@10ebd4e80eae8a5bc5147c0a36ebb568d1b277bd
        uses: workflow/nix-shell-action@v3.3.2
        with:
          interpreter: # optional, default is bash
          packages: # optional, default is bash
          flakes: # optional, default is 
          flakes-from-devshell: # optional
          # The actual script to execute in the shell
          script: echo "Current directory: $(pwd)"
          # Execute the script inside the specified working directory instead of the repository root. Example: path/to/dir
          working-directory: # optional
          
